version: "3"
services:
  server:
    image: imannost/ide-server:latest
    restart: always
    ports:
      - "20287:5000"
    container_name: ide-server
  client:
    image: imannost/ide-client:latest
    restart: always
    ports:
      - "20288:3000"
    container_name: ide-client
